#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 19 20:30:31 2020

@author: michaelboles
"""

# set up working directory
import os
os.chdir('/Users/michaelboles/Michael/Coding/2020/Insight/Project/Depreciator/scripts') 

# open new and used listings "clean_1" dataframes
import pandas as pd
all_listings_clean2 = pd.read_csv('../data/clean/all_listings_clean_2.csv')

### PLOT SUMMARY DATA ###

# pull prices for histogram
prices = all_listings_clean2['Price']

# set up statistics text box
import numpy as np
prices_mean = round(np.average(prices))
prices_median = np.median(prices)
prices_stdev = np.std(prices)
prices_textbox = 'Average = $%.0f \nMedian = $%.0f \nStdev = $%.0f' % (prices_mean, prices_median, prices_stdev)

# plot prices histogram
from plotfunctions import plothist
binwidth = 1000
plothist(prices, 
         binwidth, 
         prices_textbox, 
         0, 70000, 
         'Price ($)', 
         'Counts', 
         '../images/Prices.png')


### PLOT DEPRECIATION CURVE ###

# select one make/model combination
all_listings_clean2.columns
honda_civic = all_listings_clean2[all_listings_clean2['Model'] == 'Civic']

# plot one depreciation curve

